- go.mod
- go.sum
- pam/vplugin/control.go
- pam/vplugin/logging.go
- pam/vplugin/logging_test.go
* can be used to capture logs produced by plugin client/server library
* sync hclog version with plugin
> add zerolog adapter for hclog

- ops/swagger.go
- provider/caleta/service.go
- provider/docs/generate.go
- provider/docs/generated/provider_docs.go
- provider/docs/generated/provider_swagger.yaml
- ~~Converts generated swagger spec to oapi3~~
- ~~Requires [yarn dlx](https://yarnpkg.com/cli/dlx) . Conversion tool [swagger2openapi](https://www.npmjs.com/package/swagger2openapi) is used~~
- fix response objects
> Update swagger specification

- pam/vplugin/config.go
- pam/vplugin/vplugin.go
> Make plugin config generic

- CHANGELOG.md
- pam/vplugin/client.go
- pam/vplugin/vplugin.go
- pam/vplugin/vplugin_server.go
- some renaming
- Adding plugin server code
> Adding VPlugin server

- provider/caleta/docs/index.md
- provider/evolution/docs/index.md
- provider/redtiger/docs/index.md
> Provider docs

- .github/workflows/notify-pr.yml
> remove link preview

- provider/caleta/docs/index.md
- provider/redtiger/docs/index.md
- Removed punctuation on bullet points after suggestion
> Minor copy fixes on provider doc

- pam/vplugin/config.go
Will sync change to other repos as well.
> make vplugin config consistent with snake case

- pam/amt.go
- pam/amt_test.go
> add sub method

- CHANGELOG.md
- pam/model.gen.go
- pam/pam_api.yml
- provider/caleta/model_mapper.go
- Add betcode to pam api specification
> Add Betcode to pam api

- .github/RELEASING.md
- .github/workflows/gh-workflow.yml
- .github/workflows/release.yml
- Taskfile.yml
* added version task to print version
* namespace tasks by colon (following task styleguide) and run osx build concurrently
> Trigger release using workflow dispatch

- provider/caleta/docs/index.md
- provider/evolution/docs/index.md
- provider/redtiger/docs/index.md
- Added some docs about the new config fields
- corrected position of field
> Fix and improve provider doc

- provider/caleta/gameround_service.go
- provider/caleta/gameround_service_test.go
- provider/gameround_controller.go
- provider/gameround_controller_test.go
- Add more tests
- handle error cases from game render
> Gameround fix

- provider/redtiger/test/client_test.go
- provider/redtiger/test/integration_test.go
- Remove unused skip in tests
-  Fix Todo
note, promo is not fully implemented
> Test cleanup

- main.go
stumbled over `signal.NotifyContext` which simplified signalling a little
> simplify signalling

- Dockerfile
- Taskfile.yml
* Fixed pinning apk version 
* Fixed run as non-root user
> Added linting for Dockerfile

- pam/vplugin/vplugin.go
- pam/vplugin/vplugin_server.go
- Forgot to add vplugin methods
> TransactionSupplier for vplugin

- provider/caleta/api_client.go
- provider/caleta/caletagaming-caleta-gaming_system_api_operators_guide-1.5-oapi3.yaml
- provider/caleta/models.gen.go
- provider/caleta/provider_service.go
- "default" is the default sub_partner_id
> Sub_partner_id is mandatory. Set default value

- internal/pipeline.go
- internal/pipeline_test.go
- ops/instrument_httpclient.go
- ops/instrument_httpclient_test.go
- ops/instrument_pam.go
- ops/instrument_pam_test.go
- ops/logging.go
- ops/logging_middleware.go
- ops/logging_test.go
- ops/tracing.go
- pam/genericpam/generic_client.go
- pam/vplugin/client.go
- rest/client.go
- server/server.go
* introduce pipeline concept similar to middlewares in fiber to introduce metrics without cluttering code
* move cross cutting concerns like telemetry and logging to pipeline handlers
> Added meters for http client and pam clients

- internal/pipeline/pipeline.go
- internal/pipeline/pipeline_test.go
- ops/instrument_httpclient.go
- ops/instrument_pam.go
- pam/genericpam/generic_client.go
- pam/vplugin/client.go
- rest/client.go
* Moved pipeline to its own package under internal
> Added documentation for how to use pipeline

- rest/client.go
Set max number of call attempts to 1 for idempotent requests in rest client
> Avoid resend of idempotent requests

- example/example-game-provider/models.go
- example/example-game-provider/provider_service.go
- Make example use request method of getting gamelaunch url
> Example gamelaunch
